### ISSUE TITLE
ModuleNotFoundError: No module named '__main__.hparams'; '__main__' is not a package

### ISSUE THREAD

**Issue by w632752464** [for-ai/CipherGAN#6]
Hello,I have a question to ask you. I hope you can help me solve it. I did the calculation according to your method, and the following problem occurred in the second step. I've tried my best to solve it, but I still can't.Questions as follows: 
===================================================================
E:\WorkSpace\venv\Scripts\python.exe E:/WorkSpace/CipherGAN/train.py
Traceback (most recent call last):
  File "E:/WorkSpace/CipherGAN/train.py", line 5, in <module>
    from .hparams.registry import get_hparams
ModuleNotFoundError: No module named '__main__.hparams'; '__main__' is not a package
===================================================================

**Comment by bryanlimy** [comment]
Hi, what was the command you used to run train.py?

**Comment by w632752464** [comment]
Follow your instructions.
train.py \
  --output_dir=runs/vig345 \
  --test_name="vigenere345-brown200-eval*" \
  --train_name="vigenere345-brown200-train*" \
  --hparam_sets=vigenere_brown_vocab_200

**Comment by bryanlimy** [comment]
Hi @w632752464 are you able to test with the above command?

**Comment by w632752464** [comment]
Sorry，I have been busy recently, and I tried it this morning and it is ok. The reason: Instead of downloading zip, should downloaded the source code using git. After downloading it, according to your step and it is ok.

**Comment by w632752464** [comment]
Thank you for your sincere reply!

**Comment by bryanlimy** [comment]
I am closing this issue now, please create a new one if you experience any other problem :)
